name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ELASTICSEARCH_VERSION: 8.17.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --build-arg ELASTICSEARCH_VERSION=${{ env.ELASTICSEARCH_VERSION }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-icu:${{ env.ELASTICSEARCH_VERSION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
          ELASTICSEARCH_VERSION=${{ env.ELASTICSEARCH_VERSION }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-icu:${{ env.ELASTICSEARCH_VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/elasticsearch-icu:${{ env.ELASTICSEARCH_VERSION }}
